[package]
name = "rustarus"
version = "0.1.0"
edition = "2024"

[dependencies]
uefi = "0.35"
spin = { version = "0.10", default-features = false, features = ["spin_mutex"] }
kilo-rs = { path = "../kilo-rs", default-features = false }

[profile.release]
opt-level = "s"
lto = true
panic = "abort"

[profile.dev]
panic = "abort"
